version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/configdb
      - mongo:/data/db
    networks:
      - mongo

networks:
  mongo:
    driver: bridge

volumes:
  mongo: { }